sudo: true
language: minimal

env:
  global:
    - KLANGBECKEN_DATA=data
    - KLANGBECKEN_API_SECRET=deadbeef

script:
  - docker run --rm -ti -v $PWD:/usr/src/klangbecken -w /usr/src/klangbecken onegreyonewhite/tox:centos tox
  - coverage run --source=klangbecken_api -m unittest discover
  - coverage report -m
  - liquidsoap --version
  - test -d $KLANGBECKEN_DATA || mkdir $KLANGBECKEN_DATA
  - test -f klangbecken.liq && liquidsoap --check klangbecken.liq

after_success:
  - coveralls
